export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const UPDATING_COUNTER = "UPDATING_COUNTER";
export const FINISHED_COUNTER_UPDATE = "FINISHED_COUNTER_UPDATE";

export const CHANGE_THEME = "CHANGE_THEME";
